version: '3.8'

services:
  postgres:
    container_name: updt_process_postgre
    build:
      context: ./PostgreWithFdw
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    volumes:
      - ./PostgreWithFdw/InitSql:/docker-entrypoint-initdb.d/
      - ./PostgreWithFdw/Views:/Views
      - ./PostgreWithFdw/postgresql.conf:/etc/postgresql/postgresql.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

  mongodb:
    image: mongo:latest
    container_name: updt_process_mongo_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./MongoDb/Collections/:/MongoDb/Collections/
      - ./MongoDb/AggregationPipeline/:/MongoDb/AggregationPipeline/
      - ./MongoDb/NormalizedTransformations/:/MongoDb/NormalizedTransformations/
      - ./MongoDb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    #environment:
    #  - MONGO_INITDB_ROOT_USERNAME=admin
    #  - MONGO_INITDB_ROOT_PASSWORD=admin
    #  - MONGO_INITDB_DATABASE=test
    command: mongod --bind_ip_all

#  birds:
#    image: dangtv/birds
#    container_name: updt_process_birds_editor
#    ports:
#      - "3010:3010"

