version: '3.8'

services:
  postgres:
    build:
      context: ./PostgreWithFdw
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    volumes:
      - ./PostgreWithFdw/InitSql:/docker-entrypoint-initdb.d/
      - ./PostgreWithFdw/Views:/Views

  mongodb:
    image: mongo:latest
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./MongoDb/Collections/:/Collections
      - ./MongoDb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    #environment:
    #  - MONGO_INITDB_ROOT_USERNAME=admin
    #  - MONGO_INITDB_ROOT_PASSWORD=admin
    #  - MONGO_INITDB_DATABASE=test
    command: mongod --bind_ip_all

  birds:
    image: dangtv/birds
    ports:
      - "3010:3010"

